### ISSUE TITLE
リマインド日時や、注文日時を柔軟に変更できるように管理方法の変更を検討

### ISSUE THREAD

**Issue by tamashiro-syuta** [NODASHUSEINANODA/ohana_api#124]
現状だと、リマインド日時や注文日時は、コード上にハードコーディングしている。
（変更があるかはわからないが）変更する際には直接コードをいじらないといけなく、硬い設定になっている。

今の所、変更があることは少ないと思うので、優先度はかなり低め。

案① : DBで管理
案② : 環境変数で管理

**Comment by Yuki-Miyagi** [comment]
ワイ的には、ログインしている会社ごとに、リマインド日時や注文日時を指定できる方が、柔軟性は高くなるけど、優先度は同じく低いイメージ、やるならDBで管理かな

**Comment by tamashiro-syuta** [comment]
だよね〜、
実装方法としては、毎日 注文 or リマインド のバッチ処理を書いて、実行日に 注文 or リマインド が設定されている会社があれば実行的な感じになりそうだね
