### ISSUE TITLE
mainブランチからブランチ切るんだよとかのルールをREADMEとかに書く

### ISSUE THREAD

**Issue by tamashiro-syuta** [NODASHUSEINANODA/ohana_api#173]

**Comment by tamashiro-syuta** [comment]
issue駆動開発だよとかの説明を必要そう

**Comment by tamashiro-syuta** [comment]
wikiとかでも良いかなって思ってきた

**Comment by Yuki-Miyagi** [comment]
手順的には
1. mainから開発用ブランチを切る
2. 開発用ブランチで開発する
3. 開発用ブランチでプルリクを作成
4. レビュー完了
5. 開発用ブランチをstagingブランチにマージ
6. stagingをデプロイ後、修正箇所を確認
7. 問題なければ、mainにマージ後、デプロイ
だけど、認識合ってる？

**Comment by Yuki-Miyagi** [comment]
@tamashiro-syuta Wikiに追加してます！

**Comment by tamashiro-syuta** [comment]
確認した！ありがとう！！！！

**Comment by tamashiro-syuta** [comment]
closeします！！！
