### ISSUE TITLE
READMEにSTGにログインする時のパスワード情報について記載する

### ISSUE THREAD

**Issue by tamashiro-syuta** [NODASHUSEINANODA/ohana_api#180]
`seed.rb` を見ればわかるけど、時間使って探させる情報でもないので、READMEに記載した方がよさげかも。

あと、STG以外で使うななよって忠告もセットで、DBリセットするコマンドも乗せてても良いかも。
slackに書いてるの探しに行くの手間なので

**Comment by Yuki-Miyagi** [comment]
書きます！

**Comment by Yuki-Miyagi** [comment]
とりあえず、追加したので、さらっと確認お願いします。

**Comment by tamashiro-syuta** [comment]
対応ありがとう！closeするね！
